name: Build release zips
run-name: ${{ github.actor }} is  doing someting
on: 
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Checkout Me
        uses: actions/checkout@v3
      - name: Checkout jt
        uses: actions/checkout@v3
        with:
          repository: jotego/jtbin
          path: './jtbin'
          fetch-depth: '0'
      - name: Run PHP script
        shell: bash
        run: |
          php -f .github/build_releases_hash.php
      - name: Commit zips
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating releases
          file_pattern: '*.zip'
