name: make a zip
run-name: ${{ github.actor }} is  doing someting
on: 
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Me
        uses: actions/checkout@v3
      - name: Checkout jt
        uses: actions/checkout@v3
        with:
          repository: mattpannella/jtbin
          path: './jtbin'
      - name: Shell
        shell: bash
        run: |
          cd jtbin;
          zip ../test.zip pocket/Cores/jotego.jtdd/*;
          cd ..;
      - name: Commit 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: testing this thing
          file_pattern: 'test.zip'
